steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['pull', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:canary']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:canary', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:stable']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:stable']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:canary', 'github.com/m-okeefe/helloworld', '-f', 'Dockerfile']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['tag', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:canary', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:v-$COMMIT_SHA']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:v-$COMMIT_SHA']
  timeout: 500s
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/mokeefe-sandbox/github.com/m-okeefe/helloworld:canary']
  timeout: 500s